- hosts: "{{ server }}"
  become: true
  vars:
    ansible_become_pass: ansible
  tasks:
  - name: Crear CA, Certificados
    block:
    #####################
    ##### CREAR CARPETA##
    #####################

    - name: Crear directorio /AFC/security
      ansible.builtin.file:
        path: /AFC/security
        state: directory
        mode: '0755'

    rescue:

    - name: Forzar finalizacion playbook
      meta: end_play
