- hosts: "{{ server }}"
  remote_user: root
  tasks:
  - name: Ping
    block:

    - name: Ping server
      ansible.builtin.ping:

    rescue:

    - name: Forzar finalizacion playbook
      meta: end_play
